server:
  port: 12302
  context-path: /rms-boot

###===  文件上传处理   =====##
file:
  upload:
    method: local
    store:
      path: D:/nginx-1.2.8/html/cms
    access:
      domain: http://localhost/cms

