server:
  port: 12302
  context-path: /rms-boot


##======短息提心查询======#
rent:
  due:
    urge:
      cron: 0 2 * * * ?

###===  文件上传处理   =====##
file:
  upload:
    method: local
    store:
      path: D:/nginx-1.2.8/html/cms
    access:
      domain: http://localhost/cms

