DROP TABLE IF EXISTS T_APP_INTERFACE_LOG;
DROP TABLE IF EXISTS T_APP_CHECK_CODE;
DROP TABLE IF EXISTS T_APP_TOKEN;
DROP TABLE IF EXISTS T_APP_QUESTIONS;
DROP TABLE IF EXISTS T_MESSAGE;
DROP TABLE IF EXISTS t_house_ad;
DROP TABLE IF EXISTS T_REPAIR;
DROP TABLE IF EXISTS t_service_user_complain;
DROP TABLE IF EXISTS t_phone_record;

CREATE TABLE T_REPAIR
(
  ID                 VARCHAR(64)         NOT NULL,
  USER_ID            VARCHAR(64) COMMENT '报修人ID',
  USER_NAME          VARCHAR(20) COMMENT '报修人',
  USER_MOBILE        VARCHAR(20) COMMENT '报修电话',
  REPAIR_MOBILE      VARCHAR(20) COMMENT '报修联系电话',
  EXPECT_REPAIR_TIME VARCHAR(50) COMMENT '期望维修时间',
  CONTRACT_ID        VARCHAR(64) COMMENT '合同号',
  ROOM_ID            VARCHAR(64) COMMENT '房间号',
  DESCRIPTION        VARCHAR(500) COMMENT '报修描述',
  KEEPER             VARCHAR(20) COMMENT '管家',
  KEEPER_MOBILE      VARCHAR(20) COMMENT '管家电话',
  STATUS             VARCHAR(10) COMMENT '状态',
  CREATE_BY          VARCHAR(64) COMMENT '创建者',
  CREATE_DATE        DATETIME COMMENT '创建时间',
  UPDATE_BY          VARCHAR(64) COMMENT '更新者',
  UPDATE_DATE        TIMESTAMP COMMENT '更新时间',
  REMARKS            VARCHAR(255) COMMENT '备注信息',
  DEL_FLAG           CHAR(1) DEFAULT '0' NOT NULL
  COMMENT '删除标记',
  PRIMARY KEY (ID)
)
  COMMENT = '报修表';

CREATE TABLE t_service_user_complain (
  ID           VARCHAR(64) NOT NULL,
  USER_ID      VARCHAR(64) COMMENT '投拆人',
  service_user VARCHAR(64) COMMENT '被投拆人,服务管家',
  content      VARCHAR(500) COMMENT '投拆内容',
  CREATE_BY    VARCHAR(64) COMMENT '创建者',
  CREATE_DATE  DATETIME COMMENT '创建时间',
  UPDATE_BY    VARCHAR(64) COMMENT '更新者',
  UPDATE_DATE  TIMESTAMP COMMENT '更新时间',
  REMARKS      VARCHAR(255) COMMENT '备注信息',
  DEL_FLAG     CHAR(1) DEFAULT '0'
  COMMENT '删除标记',
  PRIMARY KEY (ID)
)
  COMMENT ='管家投拆记录';

CREATE TABLE t_house_ad
(
  ID                  VARCHAR(64)         NOT NULL,
  ad_name             VARCHAR(64) COMMENT '广告名称',
  ad_type             VARCHAR(2) COMMENT '广告类型 0:图片广告 1:房源链接式广告',
  PROPERTY_PROJECT_ID VARCHAR(64) COMMENT '物业项目',
  BUILDING_ID         VARCHAR(64) COMMENT '楼宇',
  HOUSE_ID            VARCHAR(64) COMMENT '房屋',
  ROOM_ID             VARCHAR(64) COMMENT '房间',
  ad_value            VARCHAR(64) COMMENT '房源ID',
  ad_url              VARCHAR(255) COMMENT '广告图片地址',
  CREATE_BY           VARCHAR(64) COMMENT '创建者',
  CREATE_DATE         DATETIME COMMENT '创建时间',
  UPDATE_BY           VARCHAR(64) COMMENT '更新者',
  UPDATE_DATE         TIMESTAMP COMMENT '更新时间',
  REMARKS             VARCHAR(255) COMMENT '备注信息',
  DEL_FLAG            CHAR(1) DEFAULT '0' NOT NULL
  COMMENT '删除标记',
  PRIMARY KEY (ID)
)
  COMMENT = '广告';

CREATE TABLE T_MESSAGE
(
  ID          VARCHAR(64)         NOT NULL,
  TITLE       VARCHAR(200) COMMENT '消息标题',
  CONTENT     VARCHAR(500) COMMENT '消息内容',
  TYPE        VARCHAR(10) COMMENT '消息类型',
  SENDER      VARCHAR(30) COMMENT '发送人',
  RECEIVER    VARCHAR(30) COMMENT '接收人',
  STATUS      VARCHAR(10) COMMENT '状态',
  CREATE_BY   VARCHAR(64) COMMENT '创建者',
  CREATE_DATE DATETIME COMMENT '创建时间',
  UPDATE_BY   VARCHAR(64) COMMENT '更新者',
  UPDATE_DATE TIMESTAMP COMMENT '更新时间',
  REMARKS     VARCHAR(255) COMMENT '备注信息',
  DEL_FLAG    CHAR(1) DEFAULT '0' NOT NULL
  COMMENT '删除标记',
  PRIMARY KEY (ID)
)
  COMMENT = '消息表';

CREATE TABLE T_APP_CHECK_CODE
(
  ID     VARCHAR(64) NOT NULL,
  PHONE  VARCHAR(20) COMMENT '手机号码',
  CODE   VARCHAR(64) COMMENT '验证码',
  EXPRIE TIMESTAMP COMMENT '过期时间',
  PRIMARY KEY (ID)
)
  COMMENT = '验证码';


CREATE TABLE T_APP_TOKEN
(
  ID     VARCHAR(64) NOT NULL,
  PHONE  VARCHAR(20) COMMENT '手机号码',
  TOKEN  VARCHAR(200) COMMENT 'TOKEN',
  EXPRIE TIMESTAMP COMMENT '过期时间',
  PRIMARY KEY (ID)
)
  COMMENT = 'TOKEN';

CREATE TABLE T_APP_INTERFACE_LOG
(
  ID          VARCHAR(64) NOT NULL,
  INTERFACE   VARCHAR(200) COMMENT '接口名',
  REQUEST     VARCHAR(1000) COMMENT 'request',
  RESPONSE    VARCHAR(1000) COMMENT 'response',
  IS_SUCCESS  CHAR(1) COMMENT '是否调用成功',
  INVOKE_TIME TIMESTAMP COMMENT '创建者',
  RETURN_TIME TIMESTAMP COMMENT '创建时间',
  PRIMARY KEY (ID)
)
  COMMENT = '接口调用日志';

CREATE TABLE T_APP_QUESTIONS
(
  ID          VARCHAR(64)         NOT NULL,
  QUESTION    VARCHAR(2000) COMMENT '问题',
  ANSWER      VARCHAR(2000) COMMENT '回答',
  TYPE        VARCHAR(1) COMMENT '类型',
  SORT        INT COMMENT '排序',
  CREATE_BY   VARCHAR(64) COMMENT '创建者',
  CREATE_DATE DATETIME COMMENT '创建时间',
  UPDATE_BY   VARCHAR(64) COMMENT '更新者',
  UPDATE_DATE TIMESTAMP COMMENT '更新时间',
  REMARKS     VARCHAR(255) COMMENT '备注信息',
  DEL_FLAG    CHAR(1) DEFAULT '0' NOT NULL
  COMMENT '删除标记',
  PRIMARY KEY (ID)
)
  COMMENT = '常见问题';

CREATE TABLE t_phone_record (
  `id`            VARCHAR(64) NOT NULL,
  `project_id`    VARCHAR(64)  DEFAULT NULL,
  `building_id`   VARCHAR(64)  DEFAULT NULL,
  `house_id`      VARCHAR(64)  DEFAULT NULL,
  `room_id`       VARCHAR(64)  DEFAULT NULL,
  `flats_tag`     TINYINT(4)   DEFAULT NULL
  COMMENT '公寓类型',
  `ali_user_id`   VARCHAR(64)  DEFAULT NULL,
  `zhima_open_id` VARCHAR(64)  DEFAULT NULL,
  `room_code`     VARCHAR(64)  DEFAULT NULL
  COMMENT '房源编号',
  `record_time`   DATETIME     DEFAULT NULL
  COMMENT '电话记录时间',
  `CREATE_BY`     VARCHAR(64)  DEFAULT NULL,
  `CREATE_DATE`   DATETIME     DEFAULT NULL,
  `UPDATE_BY`     VARCHAR(64)  DEFAULT NULL,
  `UPDATE_DATE`   DATETIME     DEFAULT NULL,
  `REMARKS`       VARCHAR(255) DEFAULT NULL,
  `DEL_FLAG`      CHAR(1)      DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  COMMENT = '支付宝预约看房电话记录表';